---
# cf-deployment uses system_domain as metron agent deployment.
# Use this to override metron agent deployment name in the loggregator_agent addon
- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggregator_agent/properties/deployment?
  value: ((loggregator_agent_deployment))
